
modLoader="javafml"
loaderVersion="[40,)"
license="All rights reserved"
issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/"
[[mods]]
modId="ba_bt"
version="${file.jarVersion}"
displayName="Brass-Amber BattleTowers"
displayURL="https://www.curseforge.com/minecraft/mc-mods/brassamberbattletowers"
logoFile="BrassAmberBattleTowers.png"
credits='''Mod Inspired by BattleTower Mod in YogBox
           Translations by: SamleGamer, Kzeroko, RockYl, and BlackShadow77
           Music:
                Land Tower: Ancestry by Lena Raine (Edit by Milamber)
                Ocean Tower: Void by DM DOKURO (Edit by Brass)
                Core Tower: So Below by Lena Raine (Edit by Pion)
                Nether Tower: Pigstep FHP Remix (Unedited)
                End Tower:  Complex Radiation by LudoCrypt
                Sky Tower: Clouds by Emile van Kreiken
           '''


authors="Milamber, Brass_Herbalist, X, DerToaster"
description='''BattleTowers Mod from YogBox/Tekkit days with revamped towers and bosses.
Stays true to the core of BattleTowers with new item textures made by Brass_Herbalist, and new towers designed by
Brass_Herbalist and built by Milamber with Ai/Entities by X and Der Toaster.
'''
[[dependencies.ba_bt]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.ba_bt]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
# [[dependencies.ba_bt]]
  #  modId="lootr"
  #  mandatory=false
  #  versionRange="[0.2.20.57,)"
  #  ordering="NONE"
  #  side="BOTH"


