
modLoader="javafml"
loaderVersion="[40,)"
license="All rights reserved"
issueTrackerURL="https://github.com/BrassAmber-Mods/Brass_Amber_BattleTowers/issues"
[[mods]]
modId="ba_bt"
version="${file.jarVersion}"
displayName="Brass-Amber BattleTowers"
displayURL="https://www.curseforge.com/minecraft/mc-mods/brassamberbattletowers"
logoFile="BrassAmberBattleTowers.png"
credits='''Inspired by BattleTowers from YogBox
           Translations by: SamleGamer, Kzeroko, RockYl, and BlackShadow77
           Music:
                Land Tower: Ancestry by Lena Raine
                Ocean Tower: Dragonfish by C418
                Core Tower: So Below by Lena Raine
                Nether Tower: Rubedo by Lena Raine
                End Tower:  Complex Radiation by LudoCrypt
                Sky Tower: Clouds by Emile van Kreiken
           '''


authors="Milamber, Brass_Herbalist, X, DerToaster"
description='''Mod is a continuation of BattleTowers Mod from YogBox/Tekkit days with revamped towers and bosses.
Stays true to the core of BattleTowers with new item textures made by Brass_Herbalist, and new towers designed by
Brass_Herbalist and built by Milamber with Ai/Entities by X, Der Toaster, and Milamber.
'''
[[dependencies.ba_bt]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.ba_bt]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
# [[dependencies.ba_bt]]
  #  modId="lootr"
  #  mandatory=false
  #  versionRange="[0.2.20.57,)"
  #  ordering="NONE"
  #  side="BOTH"


